version: "3"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - $HOME/.ssh/:/home/vscode/.ssh/
    command: sleep infinity
